# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-09 13:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Human',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Surname', models.CharField(max_length=100)),
                ('Birthday', models.DateField()),
                ('PlaceOfBirth', models.CharField(max_length=100)),
                ('Gender', models.CharField(max_length=15)),
                ('Age', models.PositiveIntegerField()),
                ('INN', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HumanDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DocumentType', models.CharField(max_length=20)),
                ('DocumentNumber', models.PositiveIntegerField()),
                ('DocumentDate', models.DateField()),
                ('human', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medcard.Human')),
            ],
        ),
    ]
