# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-10 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medcard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human',
            name='Gender',
            field=models.CharField(choices=[('ML', 'Male'), ('FM', 'Female')], max_length=2),
        ),
    ]
