# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 16:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medcard', '0002_auto_20160610_1009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='human',
            old_name='Age',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='human',
            old_name='Birthday',
            new_name='birthday',
        ),
        migrations.RenameField(
            model_name='human',
            old_name='Gender',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='human',
            old_name='INN',
            new_name='inn',
        ),
        migrations.RenameField(
            model_name='human',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='human',
            old_name='PlaceOfBirth',
            new_name='place_of_birth',
        ),
        migrations.RenameField(
            model_name='human',
            old_name='Surname',
            new_name='surname',
        ),
        migrations.RenameField(
            model_name='humandocument',
            old_name='DocumentDate',
            new_name='documentDate',
        ),
        migrations.RenameField(
            model_name='humandocument',
            old_name='DocumentNumber',
            new_name='document_number',
        ),
        migrations.RenameField(
            model_name='humandocument',
            old_name='DocumentType',
            new_name='document_type',
        ),
    ]
