# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medcard', '0003_auto_20160620_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human',
            name='gender',
            field=models.CharField(choices=[('муж', 'Male'), ('жен', 'Female')], max_length=3),
        ),
    ]
