# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medcard', '0004_auto_20160620_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human',
            name='gender',
            field=models.CharField(choices=[('m', 'Male'), ('f', 'Female')], max_length=1),
        ),
    ]
