# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 14:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('medcard', '0006_auto_20160621_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='human',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 22, 14, 7, 25, 316306, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='human',
            name='age',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='human',
            name='gender',
            field=models.CharField(choices=[('m', 'Мужской'), ('f', 'Женский')], max_length=1),
        ),
    ]
