# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 09:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('medcard', '0007_auto_20160622_1707'),
    ]

    operations = [
        migrations.RenameField(
            model_name='humandocument',
            old_name='documentDate',
            new_name='document_date',
        ),
        migrations.AlterField(
            model_name='human',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 28, 9, 1, 24, 83117, tzinfo=utc)),
        ),
    ]
